version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: is-lab1
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: is1
      JWT_KEY: ${JWT_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: is1
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
